apiVersion: apps/v1
kind: Deployment
metadata:
  name:  postgres-db
  namespace: default
  labels:
    app:  postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 2
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  postgres
        image: postgres:latest
        env:
         - name: POSTGRES_PASSWORD
           value: "examplepassword"
         - name: POSTGRES_USER
           value: "exampleuser"
         - name: POSTGRES_DB
           value: "exampledb"
        ports:
        - containerPort:  5432
          name:  postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-db-volume
      volumes:
        - name: postgres-db-volume
          persistentVolumeClaim:
           claimName: postgres-db-pvc
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: default
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
  