apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: default
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 2
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
         - name: POSTGRES_PASSWORD
           value: "examplepassword"
         - name: POSTGRES_USER
           value: "exampleuser"
         - name: POSTGRES_DB
           value: "exampledb"
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-db-volume
      volumes:
        - name: postgres-db-volume
          persistentVolumeClaim:
            claimName: postgres-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: default
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
