apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: default
  labels:
    app: roammatesapp
spec:
  selector:
    matchLabels:
      app: roammatesapp
  replicas: 3
  template:
    metadata:
      labels:
        app: roammatesapp
    spec:
      containers:
        - name: web
          image: benji918/roammatesapp:latest
          ports:
            - containerPort: 8000
         
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: default
spec:
  selector:
    app: roammatesapp
  ports:
    - name: web
      protocol: TCP
      port: 8000
      targetPort: 8000
